title: "Footer"
description: |
  The footer should be used as a easy social media directory. This will apear on every page. Once selected, the user will be directed to my Instagram.
  I only choose to display my Instagram because that is the only way I'd like to be contacted, it helps by not having to go to a bunch of different platforms to see if I've been contacted. I also decided to use my accent color for the footer text because I wanted it to stand out.
