title: "Navigation"
description: |
    The Navigation will be placed on the left hand side of the page at all times unless viewed on a smaller screen at which point it will be centered for easy website navigation.
